### PR TITLE
Added library API documentation

### PR DESCRIPTION
**Pull request by gopika-na**
Ready for review

### CODE REVIEW

**Comment by kristinpeterson** [comment]
@mentos @stream7 can either of you please review when you have a moment?

**Comment by gopika-na** [comment]
@kristinpeterson Thanks for the review comments
I will remove the docs folder & leave the inline documentation.
We are using JS-DOC in Node-JS & Tessel also.
Do you want us to remove the docs folder from Node-JS & Tessel also

**Comment by kristinpeterson** [comment]
@gopika-na yes please, and thank you!  We will share details on the plan for automating user documentation via new GitHub issues in those repositories.

**Comment by gopika-na** [comment]
@kristinpeterson Removed docs folder. Ready for review.

**Comment by kristinpeterson** [comment]
@mentos can you please review when you have a moment?

**Comment by gopika-na** [comment]
Ready for review

**Pull request merged**
